apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-html

data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Shop Service</title>

      <style>
        body {
          text-align: center;
          font-family: Arial;
          margin-top: 100px;
          background-color: #dff0d8;
        }
      </style>
    </head>

    <body>

      <h1>Welcome to SHOP Service</h1>

      <h2>Products Page</h2>

      <a href="/">
        <button>Go Home</button>
      </a>

    </body>
    </html>