apiVersion: v1
kind: ConfigMap

metadata:
  name: cart-html

data:
  cart/index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Cart Service</title>
    </head>

    <body style="text-align:center; margin-top:100px;">

      <h1>Welcome to CART Service</h1>

      <a href="/">
        <button>Home</button>
      </a>

    </body>
    </html>