apiVersion: v1
kind: ConfigMap

metadata:
  name: home-html

data:
  index.html: |
    <!DOCTYPE html>
    <html>

    <head>
      <title>Home Service</title>

      <style>
        body {
          text-align: center;
          font-family: Arial;
          margin-top: 100px;
          background-color: #f2f2f2;
        }

        button {
          padding: 15px 30px;
          margin: 20px;
          font-size: 20px;
          border: none;
          background-color: orange;
          color: white;
          border-radius: 10px;
          cursor: pointer;
        }
      </style>
    </head>

    <body>

      <h1>Welcome to HOME Service</h1>

      <a href="/shop">
        <button>Shop</button>
      </a>

      <a href="/cart">
        <button>Cart</button>
      </a>

    </body>
    </html>

  default.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }
    }